config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :employees, controllers: {
    sessions: 'sessions',
    invitations: 'invitations',
    passwords: 'passwords'
  }

  resources :employees, except: %i[new edit create] do
    patch :skill_experience
    resources :projects, except: %i[edit show index]
  end
  resources :skills, except: %i[new edit]
  resources :archive, only: %i[index destroy]

  post :wishes, to: 'application#wishes'
  root to: 'employees#index'
end

app/models/employee.rb
# frozen_string_literal: true

class Employee < ApplicationRecord
  include Filterable
  extend FriendlyId

  FILTERS = %i[role office department status]

  has_many :resource_skills, dependent: :destroy
  has_many :skills, through: :resource_skills

  has_many :projects, dependent: :destroy
  has_many :active_projects, ->{ where(active: true) }, class_name: 'Project', dependent: :destroy
  has_many :manager_active_projects, ->{ where(active: true) },
           class_name: 'Project', dependent: :destroy, foreign_key: :manager_id

  has_many :own_skills, class_name: 'Skill'

  has_many :manager_developers, foreign_key: :manager_id, class_name: 'EmployeeManager'
  has_many :developers, through: :manager_developers, source: :developer

  has_many :developer_managers, foreign_key: :developer_id, class_name: 'EmployeeManager'
  has_many :managers, through: :developer_managers, source: :manager

  has_one :image, as: :imageable, dependent: :destroy

  friendly_id :friendly_name, use: :slugged

  devise :invitable, :database_authenticatable, :recoverable,
         :rememberable, :trackable, :validatable

  enum role: %i[other developer manager team_lead admin system_administrator]
  enum department: %i[ruby php js sys_admins managers other_department game_dev ios android markup java]
  enum office: %i[managers_office ruby_office central firsts uglyash gamers admins remote lviv]
  enum status: %i[free partially_busy busy]

  default_scope { where(deleted: false) }

  FILTERS.each do |filter|
    scope filter, ->(value) { where(filter => value)}
  end

  scope :deleted, -> { unscoped.where(deleted: true) }
  scope :search, ->(term) do
    return all unless term
    where("(first_name ILIKE ?) OR ((first_name || ' ' || last_name) ILIKE ?)", "%#{term}%", "%#{term}%")
  end

  accepts_nested_attributes_for :image, :skills, :resource_skills

  def self.filter_skills(employee, skills_array)
    employee.select do |empl|
      empl if empl.skills.collect(&:name).any? do |skill|
        skills_array.include?(skill)
      end
    end
  end

  def name
    "#{first_name} #{last_name}"
  end

  def friendly_name
    email.split('@').first.tr('.', '_')
  end

  def avatar
    image&.image_url || 'user.png'
  end

  def delete
    update(deleted: true)
  end

  def restore
    update(deleted: false)
  end

  def admin?
    super || self.grant_admin_permissions
  end

  def developer_without_ap?
    self.developer? && !admin?
  end

  def self.me
    find_by(email: ENV['MY_EMAIL'])
  end
end

app/controllers/employees_controller.rb
# frozen_string_literal: true

class EmployeesController < ApplicationController
  before_action :find_employee, except: %i[index skill_experience]
  before_action :load_data, only: %i[index show]

  def index
    redirect_to current_employee if current_employee.developer_without_ap?
  end

  def show
    redirect_to current_employee if current_employee != @employee && current_employee.developer_without_ap?
    @employee.build_image unless @employee.image
    @project = @employee.projects.new
    @project.build_image

    respond_to do |format|
      format.html
      format.json if current_employee == @employee
      format.pdf do
        render pdf: "#{@employee.slug}",
               template: 'employees/show_pdf.html.haml',
               locals: { keys: params.permit(params.keys).to_h },
               layout: 'pdf.html.haml',
               encoding: 'UTF-8',
               show_as_html: params.key?('debug'),
               margin: { top: 15, bottom: 15, left: 20, right: 20 }
      end
    end
  end

  def update
    authorize @employee
    @employee.additional = employee_params[:additional] || {}
    if @employee.update(employee_params)
      flash[:notice] = 'Successfully updated'
    else
      flash[:danger] = 'Is not updated'
    end
    redirect_to employee_path(@employee)
  end

  def destroy
    authorize @employee
    if @employee.delete
      flash[:notice] = 'Successfully deleted'
    else
      flash[:danger] = 'Is not deleted'
    end
    redirect_to employees_path
  end

  def skill_experience
    employee = Employee.includes(:skills).friendly.find(params[:employee_id])
    skill = employee.resource_skills.find params.dig(:skill_experience, :id)
    skill.update_attributes!(skill_experience_params)
    redirect_to employee
  end

  private

  def find_employee
    @employee = Employee.includes(projects: [:skills], skills: [:resource_skills]).friendly.find(params[:id])
  end

  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :main_skill, :description, :email,
                                     :phone, :office, :role, :skype, :department, :upwork, :status,
                                     additional: {}, image_attributes: {}, skill_ids: [],
                                     manager_ids: [], developer_ids: [])
  end

  def skill_experience_params
    params.require(:skill_experience).permit(:id, :experience, :level)
  end

  def pundit_user
    current_employee
  end
end

app/helpers/employees_helper.rb
# frozen_string_literal: true

module EmployeesHelper
  def role(employee)
    return 'Owner' if employee.admin?
    employee.role.humanize
  end

  def able_edit
    return unless block_given?
    yield if able_edit?
  end

  def able_edit?
    current_employee == @employee ||
      current_employee&.admin? ||
      (current_employee&.manager? && (@employee.developer? || @employee.team_lead?)) ||
      (current_employee&.team_lead? && current_employee&.department == @employee.department && @employee.developer?)
  end

  def able_change_role?
    current_employee&.manager? || current_employee&.admin?
  end

  def pluralize(body, size = nil)
    return body.pluralize unless size
    parts = super(size, body).split
    "#{ parts&.last&.capitalize } (#{ parts&.first })"
  end
end

app/views/employees/_employee_list.html.haml
.section.list.container-fluid.col-3
  %h3.d-flex.align-items-center
    .flex-grow-0
      %i.fa.fa-long-arrow-left.pointable#toggleEmployees
    .flex-grow-1.text-center List

  .content
    - if @employees.present?
      .row
        .col-12
          %small.float-right
            Employees:
            = @employees&.values&.flatten&.size

      %ul
        - @employees.each do |department, employees|
          %h4
            %span{id: department}= department&.humanize
            .float-right= employees.size

          - employees.each do |employee|
            %li{class: "#{employee.status}"}= link_to_with_filters employee.name, employee_path(employee)
          &nbsp;
    - else
      %h3.text-center No one found :(

app/views/employees/_filters.html.haml
.section.filters.container-fluid.col-3
  %h3.d-flex.align-items-center
    .flex-grow-0
      %i.fa.fa-long-arrow-left.pointable#toggleFilters
    .flex-grow-1.text-center Filters

  .content
    %p
    = form_tag '', method: :get, enforce_utf8: false do
      .form-row
        .col-4
          .form-group
            = select_tag :office, options_for_select(Employee.offices.map { |k, v| [k.humanize, v] }, params[:office]), prompt: 'Office', class: 'form-control'
        .col-4
          .form-group
            = select_tag :role, options_for_select(Employee.roles.reject { |r| r == 'admin' }.map { |k, v| [k.humanize, v] }, params[:role]), prompt: 'Role', class: 'form-control'
        .col-4
          .form-group
            = select_tag :department, options_for_select(Employee.departments.map { |k, v| [k.humanize, v] }, params[:department]), prompt: 'Department', class: 'form-control'
      .form-row
        .col-4
          .form-group
            = select_tag :status, options_for_select(Employee.statuses.map { |k, v| [k.humanize, v] }, params[:status]), prompt: 'Status', class: 'form-control'
      .form-row
        .col-12
          .form-group
            - @skills.to_a.group_by(&:skill_type).each do |skill_type, skills|
              %h4= skill_type&.humanize
              %p
                .form-row
                  - skills.each_slice(skills.size / 3) do |skill_slice|
                    .col-4
                      - skill_slice.each do |skill|
                        %label.form-check-label
                          = check_box_tag 'skills[]', skill.name, params[:skills]&.include?(skill.name), id: "skill_#{skill.id}"
                          = skill.name
                        %br

      .position-relative
        .filter-area
          = submit_tag 'Filter', class: 'btn btn-outline-success', name: nil
          &nbsp;
          - if params[:office] || params[:role] || params[:department] || params[:skills]
            = link_to 'Reset filters', employees_path, class: 'btn btn-outline-secondary'

app/views/employees/_form.html.haml
= form_for @employee do |f|
  .form-row
    .col-6
      .form-group
        = f.label :first_name
        = f.text_field :first_name, placeholder: true, class: 'form-control'
    .col-6
      .form-group
        = f.label :last_name
        = f.text_field :last_name, placeholder: true, class: 'form-control'
  .form-row
    .col
      .form-group
        = f.label :email
        = f.text_field :email, placeholder: true, class: 'form-control'
    - if able_change_role?
      .col-6
        .form-group
          = f.label :status
          = f.select :status, Employee.statuses.keys.map { |o| [o.humanize, o] }, { include_blank: true }, class: 'form-control'
  .form-row
    .col-12
      .form-group
        = f.label :upwork
        = f.text_field :upwork, placeholder: true, class: 'form-control'
  .form-row
    .col-6
      .form-group
        = f.label 'Main Skill ?', title: 'Can be any string. Represents developer main direction: FullStack Ruby\Rails.'
        = f.text_field :main_skill, placeholder: true, class: 'form-control'
    .col-6
      .form-group
        = f.label :phone
        = f.text_field :phone, placeholder: true, class: 'form-control'
  .form-row
    .col-6
      .form-group
        = f.label :office
        = f.select :office, Employee.offices.keys.map { |o| [o.humanize, o] }, {}, class: 'form-control'
    .col-6
      .form-group
        = f.label :skype
        = f.text_field :skype, placeholder: true, class: 'form-control'
  .form-row
    - if current_employee.admin?
      .col-6
        .form-group
          = f.label :role
          = f.select :role, Employee.roles.keys.map { |r| [r.humanize, r] }, {}, class: 'form-control'
    - if able_change_role?
      .col
        .form-group
          = f.label :department
          = f.select :department, Employee.departments.keys.map { |d| [d.humanize, d] }, {}, class: 'form-control'

  - if (current_employee.admin? || current_employee.manager?) && (@employee.developer? || @employee.team_lead?)
    .form-row
      .col-6
        .form-group
          = f.label 'Managers'
          = f.select :manager_ids, Employee.managers.map{ |m| [m.name, m.id] }, {}, { class: 'select2-field', id: 'managersSelector', multiple: :multiple, class: 'form-control'}
  - elsif (current_employee.admin? || current_employee.manager?) && @employee.managers?
    .form-row
      .col-6
        .form-group
          = f.label 'Developers'
          = f.select :developer_ids, Employee.developer.map{ |m| [m.name, m.id] }, {}, { class: 'select2-field', id: 'developersSelector', multiple: :multiple, class: 'form-control'}
  .form-group
    .custom-file
      = f.label :image, class: 'custom-file-label'
      = f.fields_for :image do |image_fields|
        = image_fields.file_field :image, class: 'custom-file-input'
  .form-group
    = f.text_area :description, placeholder: true, cols: 12, rows: 5, class: 'form-control'
  .form-group
    %btn.btn.btn-outline-success#addAdditionalField Add additional field
  .form-group
    = f.fields_for :additional, multiple: :multiple do
      #additionalFields
        - @employee.additional&.each do |key, value|
          .form-row.with-remove
            .col-3
              .form-group
                %input.form-control{onchange: 'change(this)', placeholder: 'Key', type: 'text', value: key}
            .col-8
              .form-group
                %textarea.form-control.value{name: "employee[additional][#{key}]", placeholder: 'Value', type: 'text', cols: 2}
                  = value
            .col-1
              .form-group
                %i.fa.fa-times.text-danger.pointable{onclick: 'remove(this)'}
  .form-group
    = f.label 'Skills'
    = f.select(:skill_ids, @skills.pluck(:name, :id), {}, {class: 'select2-field', id: 'skillsSelector', multiple: :multiple, placeholder: 'Skills'})
  .form-group
    = f.submit class: 'btn btn-success'

app/views/employees/_resource_skill_form.html.haml
= form_for 'skill_experience', url: employee_skill_experience_path(@employee), method: :patch do |f|
  = f.hidden_field :id, value: resource_skill.id
  .form-group
    = f.text_field :experience, value: resource_skill.experience, class: 'form-control', placeholder: true
  .form-group
    .skills-selector.d-flex.align-items-center
      %label{ for: :experienceLevel }
        Experience level
      %div#levelIndicator{ class: "legend-detail-#{ resource_skill.level ?  resource_skill.level: 0 } size-12-px" }
    = f.range_field :level, html_options = { class: 'custom-range', id: 'experienceLevel',
     type: :range, min: 0, max: 100, step: 1, value: resource_skill.level || 0, oninput: 'updateExperienceLevel(this);' }
  .row
    .col-2
      %img.experience-level-icon#experienceLevelIcon{ src: "/evolution_#{resource_skill.level ?  resource_skill.level == 100 ? 'under' : (resource_skill.level / 20.0).round : 0 }.png" }
    .col-5
      .legend
        %div.d-flex.align-items-center.m-mx-1
          .legend-detail-100.size-12-px
          %p - I am the GOD
        %div.d-flex.align-items-center.m-mx-1
          .legend-detail-80.size-12-px
          %p - Can do anything
        %div.d-flex.align-items-center.m-mx-1
          .legend-detail-60.size-12-px
          %p - Can do
        %div.d-flex.align-items-center.m-mx-1
          .legend-detail-40.size-12-px
          %p - Can try
        %div.d-flex.align-items-center.m-mx-1
          .legend-detail-20.size-12-px
          %p - Read about it
        %div.d-flex.align-items-center.m-mx-1
          .legend-detail-0.size-12-px
          %p - Not set
    .col-5.mt-auto
      .d-flex.align-items-end.flex-column
        = f.submit class: 'btn btn-success'

app/views/employees/edit.html.haml
= render 'form'

app/views/employees/index.html.haml
.employees
  .row
    = render 'filters'
    = render 'employee_list'
    .col

app/views/employees/pdf_form.html.haml
.pdf-generator
  .title
  %h4
    Select the employee fields that you need in the PDF file:
  .checkboxes
    .form-row
      .col
        .form-check
          = label_tag do
            = check_box_tag('pdfEmployeeAll', value: 'all', class: 'form-check-input')
            Select all
    .fields
      .form-row
        .col-4
          .form-check
            = label_tag do
              = check_box_tag('mname', checked: false, class: 'form-check-input')
              Name
          .form-check
            = label_tag do
              = check_box_tag('mrole', checked: false, class: 'form-check-input')
              Role
          .form-check
            = label_tag do
              = check_box_tag('memail', checked: false, class: 'form-check-input')
              Email
        .col-4
          .form-check
            = label_tag do
              = check_box_tag('mphone', checked: false, class: 'form-check-input')
              Phone
          .form-check
            = label_tag do
              = check_box_tag('mskype', checked: false, class: 'form-check-input')
              Skype
          .form-check
            = label_tag do
              = check_box_tag('mdescription', checked: false, class: 'form-check-input')
              Description
        .col-4
          .form-check
            = label_tag do
              = check_box_tag('madditional', checked: false, class: 'form-check-input')
              Additional
          .form-check
            = label_tag do
              = check_box_tag('mskills', checked: false, class: 'form-check-input')
              Skills
          .form-check
            = label_tag do
              = check_box_tag('mprojects', checked: false, class: 'form-check-input')
              Projects
    .form-group.float-right
      = link_to 'Generate', employee_path(@employee, format: :pdf), html_options = { class: 'btn btn-outline-secondary', id: 'linkToPdf' }

app/views/employees/show.html.haml
.employees
  .row
    - unless current_employee.developer_without_ap?
      = render 'filters'
      = render 'employee_list'
    %div{ class: current_employee.developer? ? 'col-6 mx-auto' : 'col mx-auto' }
      .section.last.profile
        .row
          .col-5
            = image_tag @employee.avatar, class: 'img-fluid'
          .col-7
            - able_edit do
              %span.link.pointable{ 'data-target': '#editModal', 'data-toggle': :modal }
                Edit
              = render 'layouts/modal', { modal_id: 'editModal', modal_title: 'Edit Employee', large: true } do
                .modal-body
                  = render template: 'employees/edit'
            - if current_employee&.admin? || current_employee&.manager?
              |
              = link_to 'Delete', employee_path(@employee), method: :delete, data: { confirm: 'Are you sure?' }

            .float-right
              Export to:
              - if current_employee == @employee
                = link_to 'JSON', employee_path(@employee, format: :json), target: '_blank'
                |
              %span.link.pointable{ 'data-target': '#pdfModal', 'data-toggle': :modal }
                PDF
              = render 'layouts/modal', { modal_id: 'pdfModal', modal_title: 'Generate a PDF', large: true } do
                .modal-body
                  = render template: 'employees/pdf_form'
            %h2
              = @employee.name
              .float-right
                = (@employee.main_skill.present? ? @employee.main_skill : @employee.department).humanize
                = role(@employee)

            %h5
              Office:
              = @employee&.office&.humanize
              - if current_employee.manager? || current_employee.admin?
                %b.float-right{class: "#{@employee.status}"}= @employee&.status&.humanize

            - unless current_employee.developer? && current_employee != @employee
              %p
                Email:
                = @employee.email
                %br
                Phone:
                = @employee.phone
                %br
                Skype:
                = @employee.skype
                %br
                Upwork:
                = link_to @employee.upwork, @employee.upwork, target: :blank

            - if (current_employee.admin? || current_employee.manager?) && @employee.managers.present?
              %p
                Managers:
                - @employee.managers.each do |manager|
                  = link_to manager.name, employee_path(manager)

            - if (current_employee.admin? || current_employee.manager?) && @employee.developers.present?
              .row
                .col-2
                  Developers:
                .col-5
                  - @employee.developers.each do |developer|
                    = link_to developer.name, employee_path(developer)
                    %br

            %p
              = raw @employee.description

        - if @employee.additional.present?
          %h3 Additional information:
          .row
            .col-12
              - @employee.additional.each do |key, value|
                %p
                .row
                  .col-2
                    .bold= key.humanize + ':'
                  .col-10
                    = raw value
                  %br

        %br
        - if @employee.skills.present?
          .skills
            .float-right
              .legend.d-flex
                %div.d-flex.align-items-center.m-mx-1
                  .legend-detail-100.size-12-px
                  %p - I am the GOD
                %div.d-flex.align-items-center.m-mx-1
                  .legend-detail-80.size-12-px
                  %p - Can do anything
                %div.d-flex.align-items-center.m-mx-1
                  .legend-detail-60.size-12-px
                  %p - Can do
                %div.d-flex.align-items-center.m-mx-1
                  .legend-detail-40.size-12-px
                  %p - Can try
                %div.d-flex.align-items-center.m-mx-1
                  .legend-detail-20.size-12-px
                  %p - Read about it
                %div.d-flex.align-items-center.m-mx-1
                  .legend-detail-0.size-12-px
                  %p - Not set
            %h3 Skills
          %hr
          .row
            - employee_skills = @employee.skills.sorted(@employee.id).to_a.group_by(&:skill_type)
            - employee_skills.each do |skill_type, skills|
              %div{ class: "col-#{12 / employee_skills.size}" }
                %h5= skill_type&.humanize
                - skills.each do |skill|
                  %div{ class: "skill-#{ skill.level(@employee.id) }"}
                    - if able_edit?
                      %span.link.pointable{ 'data-target': "#editSkillModal_#{skill.id}", 'data-toggle': :modal, title: "Experience: #{skill.experience(@employee)}" }
                        = link_to skill.display_name(@employee.id), skill_path(skill, employee_id: @employee.id), remote: true
                        %br
                    - else
                      = skill.display_name(@employee.id)
                      %br

        %p
        - if @employee.projects.present?
          .row
            .col-6
              %h3 Projects
            .col-6
              - able_edit do
                %span.link.pointable{ 'data-target': '#addProjectToEmployee', 'data-toggle': :modal }
                  .float-right
                    %btn.btn.btn-outline-success Add project
                = render 'layouts/modal', { modal_id: 'addProjectToEmployee', modal_title: 'Add project', large: true } do
                  .modal-body
                    = render 'projects/form', project: @project, employee: @employee, path: employee_projects_path(@employee)
          %hr
          - if @employee.active_projects.present? || @employee.manager_active_projects.present?
            %h4 Active projects
            - if @employee.active_projects.present?
              - @employee.active_projects.each do |project|
                = render 'projects/project', project: project
                %hr
            - elsif @employee.manager_active_projects.present?
              - @employee.manager_active_projects.each do |project|
                = render 'projects/project', project: project
                %hr
          - if @employee.projects.order('created_at DESC').reject(&:active).present?
            %h4 Finished projects
            .row
              .col-12
                - @employee.projects.order('created_at DESC').reject(&:active).each do |project|
                  = render 'projects/project', project: project
                  %hr

app/views/employees/show_pdf.html.haml
.employee-pdf
  .who.full-width.d-inline-block
    - if keys[:mname] == 'true'
      .name.half-width
        %h1
          = @employee.name
    - if keys[:mrole] == 'true'
      .description.half-width
        %h2= "#{ @employee.main_skill } #{ role(@employee) }"

  .intro.full-width.d-inline-block.no-break
    - if @employee.image&.image_url
      .avatar.half-width.auto-height.float-left.mr-1.p
        = wicked_pdf_image_tag @employee.avatar, class: 'image-content'
    .info.ml-1
      %p
        - if keys[:memail] == 'true'
          Email:
          = @employee.email
          %br
        - if keys[:mphone] == 'true'
          Phone:
          = @employee.phone
          %br
        - if keys[:mskype] == 'true'
          Skype:
          = @employee.skype
          %br
  - if keys[:mdescription] == 'true'
    .description
      %p
        = raw @employee.description
  %br
  - if keys[:madditional] == 'true'
    - if @employee.additional.present?
      .additional.d-block.full-block.always-break
        %h2 Additional information:
        %hr
        .d-block
          - @employee.additional.each do |key, value|
            .d-block
              %b= key.humanize + ':'
            .d-block
              = raw value
            %br
      %br
  - if keys[:mskills] == 'true'
    - if @employee.skills.present?
      .skills.always-break
        %h2 Skills
        %hr
        .d-block
          - @employee.skills.order(skill_type: :asc).to_a.group_by(&:skill_type).each do |skill_type, skills|
            .d-block
              %p
                %h4= "#{ skill_type&.humanize.pluralize } (#{ skills.size })"
                = skills.pluck(:name).join(', ')
  - if keys[:mprojects] == 'true'
    - if @employee.projects.reject(&:new_record?).reject(&:active).present?
      .projects.always-break
        %h2 Projects
        %hr
        - @employee.projects.order('created_at DESC').reject(&:active).each do |project|
          = render 'projects/project_pdf', project: project