config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :employees, controllers: {
    sessions: 'sessions',
    invitations: 'invitations',
    passwords: 'passwords'
  }

  resources :employees, except: %i[new edit create] do
    patch :skill_experience
    resources :projects, except: %i[edit show index]
  end
  resources :skills, except: %i[new edit]
  resources :archive, only: %i[index destroy]

  post :wishes, to: 'application#wishes'
  root to: 'employees#index'
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  after_save :add_skills_to_employee
  has_one :image, as: :imageable, dependent: :destroy
  has_many :resource_skills, dependent: :destroy
  has_many :skills, through: :resource_skills

  belongs_to :employee
  belongs_to :developer, class_name: 'Employee', foreign_key: :employee_id # alias
  belongs_to :manager, class_name: 'Employee', foreign_key: :manager_id, optional: true

  accepts_nested_attributes_for :image, :skills

  validates :name, presence: true

  def add_skills_to_employee
    employee.skills << (skills - employee.skills)
  end

  def avatar
    image&.image_url || 'placeholder.png'
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :find_project, only: %i[update destroy]

  def create
    @project = Project.new(project_params)
    authorize @project
    if @project.save
      flash[:notice] = 'Successfully created'
    else
      flash[:danger] = 'Is not created'
    end
    redirect_to employee_path(project_params[:employee_id])
  end

  def update
    authorize @project
    if @project.update(project_params)
      flash[:notice] = 'Successfully updated'
    else
      flash[:danger] = 'Is not updated'
    end
    redirect_to employee_path(project_params[:employee_id])
  end

  def destroy
    authorize @project
    if @project.destroy
      flash[:notice] = 'Successfully destroyed'
    else
      flash[:danger] = 'Is not destroyed'
    end
    redirect_to employee_path(params[:employee_id])
  end

  private

  def project_params
    params.require(:project).permit(:employee_id, :name, :description,
                                    :client, :link, :repository, :active,
                                    :manager_id, :start_date, :end_date,
                                    image_attributes: {}, skill_ids: [])
  end

  def find_project
    @project = Project.find(params[:id])
  end

  def pundit_user
    current_employee
  end
end

app/views/projects/_form.html.haml
= form_for(project, url: path ) do |f|
  .form-row
    .form-group
      = f.hidden_field :employee_id, value: employee.id
  .form-row
    .col-12
      .form-group
        = f.text_field :name, class: 'form-control', placeholder: 'Name'
  .form-row
    .col-12
      .form-group
        = f.text_area :description, class: 'form-control', placeholder: 'Description'
  .form-row
    .col-12
      .form-group
        = f.text_field :client, class: 'form-control', placeholder: 'Client name'
  .form-row
    .col-6
      .form-group
        = f.text_field :link, class: 'form-control', placeholder: 'Live URL'
    .col-6
      .form-group
        = f.text_field :repository, class: 'form-control', placeholder: 'Repository URL'
  .form-row
    .col-2
      .form-group
        = f.label 'Status'
      .form-group
        = f.check_box :active, id: :checkbox_active
        = f.label 'Active', for: :checkbox_active
    .col
      .form-group
        = f.label 'Manager'
        = f.select :manager_id, Employee.managers.map { |m| [m.name, m.id] }, { include_blank: true }, { class: 'form-control', include_blank: 'Manager' }
  .form-row
    .col-12
      .form-group
        = f.label 'Skills'
        = f.select(:skill_ids, @skills.pluck(:name, :id), {}, {class: 'select2-field', multiple: :multiple, placeholder: 'Skills'})
  .form-row
    .col-12
      .form-group
        .custom-file
          = f.label :image, class: 'custom-file-label'
          = f.fields_for :image do |image_fields|
            = image_fields.file_field :image, class: 'custom-file-input'
  .form-row
    .col-12
      .form-row
        .col-6
          .form-group
            = f.label 'Start date'
            = f.date_field :start_date, class: 'form-control'
        .col-6
          .form-group
            = f.label 'End date'
            = f.date_field :end_date, class: 'form-control'
  .form-row.float-right
    .col-12
      .form-group
        = f.submit class: 'btn btn-success'

app/views/projects/_project.html.haml
.row
  .col-4
    = image_tag project.avatar, class: 'img-fluid'
  .col-8
    - able_edit do
      %span.link.pointable{ 'data-target': "#editProjectAtEmployee_#{project.id}", 'data-toggle': 'modal' }
        Edit
      = render 'layouts/modal', { modal_id: "editProjectAtEmployee_#{project.id}", modal_title: 'Edit employee project' } do
        .modal-body
          - project.image = Image.new unless project.image.present?
          = render 'projects/form', project: project, employee: @employee, path: employee_project_path(@employee, project)
      |
      = link_to 'Delete', employee_project_path(project.id, employee_id: project.employee_id), method: :delete, data: {confirm: 'Are you sure?'}

    %h3
      = project.name
      - if project.client.present?
        .float-right
          %small
            Client:
            = project.client

    - if project.manager && (@employee.developer? || @employee.team_lead?)
      Manager:
      = link_to project.manager&.name, employee_path(project.manager)
    - if project.developer && @employee.manager?
      Developer:
      = link_to project.developer&.name, employee_path(project.developer)
    %br= link_to project&.link, project&.link, target: :blank
    %br= link_to project&.repository, project&.repository, target: :blank
    %br
    - if project.start_date && project.end_date
      %i= "#{ project.start_date.strftime('%d/%m/%Y') } - #{ project.end_date.strftime('%d/%m/%Y') }"
    %br
    = raw project.description

.row
  .col-12
    %p
    = project.skills.pluck(:name).join('/ ')

app/views/projects/_project_pdf.html.haml
.project.full-width.d-inline-block.no-break
  - if project.image&.image_url
    .avatar.half-width.auto-height.float-left.mr-1.p-non-top
      = wicked_pdf_image_tag project.avatar, class: 'image-content'
  .info.ml-1
    .title
      %h4
        = project.name
      - if project.client.present?
        .client
          %b
            Client: #{ project.client }
  .details.ml-1
    %b Live:
    = project.link
    %br
    %b Repository:
    = project.repository
    - if project.start_date && project.end_date
      %p= "#{project.start_date.strftime('%d/%m/%Y')} - #{project.end_date.strftime('%d/%m/%Y')}"
      %br
    = raw project.description

%hr