config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :employees, controllers: {
    sessions: 'sessions',
    invitations: 'invitations',
    passwords: 'passwords'
  }

  resources :employees, except: %i[new edit create] do
    patch :skill_experience
    resources :projects, except: %i[edit show index]
  end
  resources :skills, except: %i[new edit]
  resources :archive, only: %i[index destroy]

  post :wishes, to: 'application#wishes'
  root to: 'employees#index'
end

app/controllers/archive_controller.rb
# frozen_string_literal: true

class ArchiveController < ApplicationController
  def index
    redirect_to current_employee if current_employee.developer_without_ap?
    @employees = Employee.deleted
  end

  def destroy
    if Employee.deleted.friendly.find(params[:id]).restore
      flash[:success] = 'Successful restored'
    else
      flash[:danger] = 'Not restored'
    end
    redirect_to archive_index_path
  end
end

app/views/archive/index.html.haml
.archive.center-horizontal
  .container
    .title
      %h2 Employees archive
    .content
      - @employees.each do |employee|
        .row
          .col-11
            = employee.name
            %br
            = employee.email
            %br
            = employee.phone
          .col-1
            = link_to 'Restore', archive_path(employee), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-success'
        - unless employee.eql? @employees[-1]
          %hr